version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # When running frontend independently, it needs to connect to a backend
      # You can modify this URL to point to your backend service
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:5000
    networks:
      - face-recognition-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  face-recognition-network:
    driver: bridge
